"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { CAPITAL_OPTIONS, FORMAT_OPTIONS, LOCATION_OPTIONS, MENU_ITEMS, formatINR, type BusinessFormat, type Decision, type GameState, type Location, type MenuItemId } from "@/lib/simulation";

const decisionLabels: Array<[Decision, string, string]> = [
  ["raise-price", "Raise prices", "Increase the average bill, but some customers may hesitate."],
  ["marketing", "Run marketing", "Spend ₹10,000 to bring more people through the door."],
  ["hire", "Hire staff", "Spend ₹18,000 to improve service capacity."],
  ["quality", "Improve quality", "Spend ₹12,000 on product and customer experience."],
  ["inventory", "Restock", "Spend ₹8,000 to protect yourself from stock shortages."],
];

type HistoryItem = { id: string; day: number; payload: { decision?: Decision; resolvedEventTitle?: string | null; revenue?: number; profit?: number; customers?: number; cash?: number; reputation?: number } };
const decisionName = (decision?: Decision) => decisionLabels.find(([id]) => id === decision)?.[1] ?? "Business decision";

export default function Home() {
  const [state, setState] = useState<GameState | null>(null);
  const [selected, setSelected] = useState<Decision | null>(null), [eventOption, setEventOption] = useState<string | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]), [historyOpen, setHistoryOpen] = useState(false);
  const [feedbackOpen, setFeedbackOpen] = useState(false), [feedbackSent, setFeedbackSent] = useState(false);
  const [celebration, setCelebration] = useState<{ title: string; message: string; day: number } | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState("");

  useEffect(() => { fetch("/api/game/session").then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to start game."); setState(d.state as GameState); }).catch((e: Error) => setError(e.message)); }, []);
  useEffect(() => { if (!state?.setupComplete) return; fetch("/api/game/history").then(async r => r.ok ? (await r.json()).history as HistoryItem[] : []).then(setHistory).catch(() => undefined); }, [state?.day, state?.setupComplete]);
  useEffect(() => { if (!state?.setupComplete || state.day < 3) return; const last = Number(localStorage.getItem("business-sim-last-feedback-day") || 0); if (state.day >= last + 3) setFeedbackOpen(true); }, [state?.day, state?.setupComplete]);

  const newBusiness = async () => { if (!confirm("Start a new business? Your current run will remain saved.")) return; setBusy(true); const r = await fetch("/api/game/new", { method: "POST" }); const d = await r.json(); setBusy(false); if (!r.ok) { setError(d.error || "Unable to start a new business."); return; } setState(d.state as GameState); setSelected(null); setEventOption(null); setHistory([]); setCelebration(null); setError(""); };
  const endDay = async () => {
    if (!state || !selected || (state.currentEvent && !eventOption)) return;
    setBusy(true); setError("");
    try {
      const r = await fetch("/api/simulate-turn", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision: selected, eventOption }) });
      const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to advance simulation.");
      const next = d.state as GameState; setState(next); setSelected(null); setEventOption(null);
      setCelebration({ day: next.day, title: `Day ${next.day} complete 🎉`, message: next.profit >= 0 ? "You made your call and your business moved forward. Keep watching what changes from day to day." : "Early losses are part of the journey. You made a decision, learned its effect, and the next day is yours to shape." });
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to advance simulation."); } finally { setBusy(false); }
  };
  const submitFeedback = async (rating: number) => { if (!state) return; const r = await fetch("/api/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, replay: rating >= 4, realism: 3, difficulty: 3, sessionDays: state.day }) }); if (r.ok) { setFeedbackSent(true); localStorage.setItem("business-sim-last-feedback-day", String(state.day)); } };

  if (!state) return <main className="shell"><div className="container loading"><div className="brand">Business Simulator</div><h1>Opening your business…</h1><p>{error || "Getting everything ready."}</p>{error && <button className="primary" onClick={() => window.location.reload()}>Try again</button>}</div></main>;
  if (!state.setupComplete) return <SetupScreen onComplete={newState => { setState(newState); setCelebration({ day: 0, title: "Congratulations! 🎉", message: "Your new business is ready. You chose the foundations — now let’s see where they take you." }); }} />;
  const statusText = state.cash <= 0 ? "Business closed" : state.day >= 91 && state.profit > 0 ? "90 days survived" : "Open for business";

  return <main className="shell"><div className="container">
    <header className="topbar"><div><div className="brand">Business Simulator</div><div className="subtle">{LOCATION_OPTIONS.find(x => x.id === state.location)?.name} · {FORMAT_OPTIONS.find(x => x.id === state.format)?.name}</div></div><div className="top-actions"><button className="secondary compact" onClick={() => setHistoryOpen(true)}>Past days</button><button className="secondary compact" onClick={newBusiness} disabled={busy}>New business</button></div></header>
    <section className="hero game-hero"><div className="day-pill">DAY {state.day}</div><h1>How will you run it today?</h1><p>{statusText}. Make one decision, see what happens, then decide again.</p>{error && <div className="notice">{error}</div>}</section>
    <section className="grid metrics"><Metric label="Cash" value={formatINR(state.cash)} /><Metric label="Revenue" value={formatINR(state.revenue)} /><Metric label="Profit" value={formatINR(state.profit)} good={state.profit >= 0} /><Metric label="Customers" value={state.customers.toLocaleString("en-IN")} /><Metric label="Reputation" value={`${state.reputation}/100`} /></section>
    {state.currentEvent && <section className="panel event-card"><div className="eyebrow">Something happened</div><h2>{state.currentEvent.title}</h2><p>{state.currentEvent.narrative}</p><div className="actions">{state.currentEvent.options.map(o => <button key={o.id} className={`action ${eventOption === o.id ? "selected" : ""}`} onClick={() => setEventOption(o.id)} disabled={busy}><strong>{eventOption === o.id ? "✓ " : ""}{o.title}</strong><small>{o.description}{o.cost ? ` · ${formatINR(o.cost)}` : ""}</small></button>)}</div></section>}
    <section className="panel decision-card"><div className="section-head"><div><div className="eyebrow">Today’s decision</div><h2>What do you want to do?</h2></div><span className="step-count">1 choice</span></div><div className="actions">{decisionLabels.map(([id, title, description]) => <button key={id} className={`action ${selected === id ? "selected" : ""}`} onClick={() => setSelected(id)} disabled={busy}><strong>{selected === id ? "✓ " : ""}{title}</strong><small>{description}</small></button>)}</div><div className="selection-line">{selected ? <>You chose <strong>{decisionName(selected)}</strong></> : "Choose the decision that feels right."}</div><button className="primary" onClick={endDay} disabled={busy || !selected || !!(state.currentEvent && !eventOption)}>{busy ? "Finishing the day…" : "Finish day →"}</button></section>
    <div className="grid lower-grid"><section className="panel"><div className="eyebrow">Your business</div><h2>Where things stand</h2><div className="market"><Row label="Service capacity" value={`${state.serviceCapacity}/day`} /><Row label="Staff" value={`${state.staff}/100`} /><Row label="Quality" value={`${state.quality}/100`} /><Row label="Inventory" value={`${state.inventory}/100`} /><Row label="Monthly rent" value={formatINR(LOCATION_OPTIONS.find(x => x.id === state.location)?.rentMonthly ?? 0)} /></div></section><section className="panel menu-card"><div className="eyebrow">Your menu</div><h2>What you sell</h2><div className="chip-list">{state.menu.map(id => <span key={id}>{MENU_ITEMS.find(x => x.id === id)?.name}</span>)}</div></section></div>
  </div>
  {celebration && <Modal onClose={() => setCelebration(null)}><div className="celebration"><div className="celebration-icon">✦</div><div className="eyebrow">{celebration.day === 0 ? "Your journey begins" : "A new day"}</div><h2>{celebration.title}</h2><p>{celebration.message}</p>{celebration.day > 0 && <div className="result-mini"><span>Revenue <strong>{formatINR(state.revenue)}</strong></span><span>Profit <strong className={state.profit >= 0 ? "positive" : "negative"}>{formatINR(state.profit)}</strong></span><span>Customers <strong>{state.customers}</strong></span></div>}<button className="primary" onClick={() => setCelebration(null)}>{celebration.day === 0 ? "Open Day 1 →" : "Continue →"}</button></div></Modal>}
  {historyOpen && <HistoryModal history={history} onClose={() => setHistoryOpen(false)} />}
  {feedbackOpen && !feedbackSent && <Modal onClose={() => setFeedbackOpen(false)}><div className="feedback-modal"><div className="celebration-icon">♥</div><div className="eyebrow">Quick question</div><h2>How are you finding the game?</h2><p>A quick rating helps us make the experience better.</p><div className="rating-row">{[1,2,3,4,5].map(r => <button key={r} className="rating" onClick={() => submitFeedback(r)} aria-label={`${r} out of 5`}>★</button>)}</div><button className="text-button" onClick={() => setFeedbackOpen(false)}>Maybe later</button></div></Modal>}
  </main>;
}

function SetupScreen({ onComplete }: { onComplete: (state: GameState) => void }) {
  const [capital, setCapital] = useState(1000000), [location, setLocation] = useState<Location>("high-footfall"), [format, setFormat] = useState<BusinessFormat>("small-cafe"), [menu, setMenu] = useState<MenuItemId[]>(["filter-coffee", "instant-coffee", "masala-chai", "bun-maska", "vada-pav", "veg-sandwich", "espresso"]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const selectedFormat = FORMAT_OPTIONS.find(x => x.id === format)!; const menuCost = useMemo(() => menu.reduce((sum, id) => sum + (MENU_ITEMS.find(x => x.id === id)?.setupCost ?? 0), 0), [menu]); const setupCost = selectedFormat.cost + menuCost + 50000 + Math.max(30000, menu.length * 15000); const reserve = capital - setupCost;
  const supports = (itemId: MenuItemId) => { const item = MENU_ITEMS.find(x => x.id === itemId)!; if (item.infrastructure === "kitchen") return format === "full-cafe"; if (item.infrastructure === "beverage") return format !== "takeaway"; return true; };
  const lockedReason = (itemId: MenuItemId) => { const item = MENU_ITEMS.find(x => x.id === itemId)!; if (item.infrastructure === "kitchen" && format !== "full-cafe") return "Needs a full kitchen"; if (item.infrastructure === "beverage" && format === "takeaway") return "Needs beverage equipment"; return ""; };
  const toggleMenu = (id: MenuItemId) => { if (!supports(id)) return; setMenu(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]); };
  useEffect(() => { setMenu(current => current.filter(supports)); }, [format]);
  const launch = async () => { setBusy(true); setError(""); try { const r = await fetch("/api/game/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ capital, location, format, menu }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to configure business."); onComplete(d.state as GameState); } catch (e) { setError(e instanceof Error ? e.message : "Unable to configure business."); } finally { setBusy(false); } };
  return <main className="shell"><div className="container setup-container"><section className="hero setup-hero"><div className="day-pill">DAY 0</div><h1>Build your business before you open it.</h1><p>Choose your budget, location, format and menu. These choices shape the journey ahead.</p></section>
    <SetupSection number="1" title="Starting capital" help="The total cash you have available to start. Whatever remains after setup becomes your working capital."><div className="actions capital-grid">{CAPITAL_OPTIONS.map(v => <button key={v} className={`action ${capital === v ? "selected" : ""}`} onClick={() => setCapital(v)}><strong>{capital === v ? "✓ " : ""}{formatINR(v)}</strong><small>Total business budget</small></button>)}</div></SetupSection>
    <SetupSection number="2" title="Choose your location" help="Location changes rent and the kind of customer traffic you can expect."><div className="actions option-grid">{LOCATION_OPTIONS.map(o => <button key={o.id} className={`action ${location === o.id ? "selected" : ""}`} onClick={() => setLocation(o.id)}><strong>{location === o.id ? "✓ " : ""}{o.name}</strong><small>{o.description}</small><em>{formatINR(o.rentMonthly)}/month</em></button>)}</div></SetupSection>
    <SetupSection number="3" title="Choose your business format" help="Your format determines capacity, infrastructure and the kind of menu you can build."><div className="actions option-grid">{FORMAT_OPTIONS.map(o => <button key={o.id} className={`action ${format === o.id ? "selected" : ""}`} onClick={() => setFormat(o.id)}><strong>{format === o.id ? "✓ " : ""}{o.name}</strong><small>{o.description}</small><em>Setup {formatINR(o.cost)} · Capacity {o.capacity}/day</em></button>)}</div></SetupSection>
    <SetupSection number="4" title="Build your menu" help="Pick what you want to sell. Your format determines which items are available."><div className="actions menu-grid">{MENU_ITEMS.map(item => { const available = supports(item.id); const selected = menu.includes(item.id); return <button key={item.id} className={`action ${selected ? "selected" : ""} ${!available ? "locked" : ""}`} onClick={() => toggleMenu(item.id)} disabled={!available}><strong>{selected ? "✓ " : ""}{item.name}</strong><small>{available ? `Setup ${formatINR(item.setupCost)} · Weekly cost ${formatINR(item.weeklyCost)}` : lockedReason(item.id)}</small></button>; })}</div></SetupSection>
    <section className="panel setup-section"><div className="step-heading"><span>5</span><div><h2 className="section-title">Ready to open?</h2><p className="step-help">Take one last look at your starting position.</p></div></div><div className="review-grid"><div><span>Starting capital</span><strong>{formatINR(capital)}</strong></div><div><span>Setup investment</span><strong>{formatINR(setupCost)}</strong></div><div><span>Cash after setup</span><strong>{formatINR(reserve)}</strong></div><div><span>Monthly rent</span><strong>{formatINR(LOCATION_OPTIONS.find(x => x.id === location)?.rentMonthly ?? 0)}</strong></div></div>{error && <div className="notice">{error}</div>}<button className="primary" onClick={launch} disabled={busy || reserve <= 0 || menu.length === 0}>{busy ? "Opening…" : `Open ${selectedFormat.name} →`}</button></section>
  </div></main>;
}
function SetupSection({ number, title, help, children }: { number: string; title: string; help: string; children: ReactNode }) { return <section className="panel setup-section"><div className="step-heading"><span>{number}</span><div><h2 className="section-title">{title}</h2><p className="step-help">{help}</p></div></div>{children}</section>; }
function Metric({ label, value, good }: { label: string; value: string; good?: boolean }) { return <div className="panel metric-card"><div className="metric-label">{label}</div><div className={`metric-value ${good ? "good" : ""}`}>{value}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="market-row"><span>{label}</span><strong>{value}</strong></div>; }
function Modal({ children, onClose }: { children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}>{children}</div></div>; }
function HistoryModal({ history, onClose }: { history: HistoryItem[]; onClose: () => void }) { return <Modal onClose={onClose}><div className="history-header"><div><div className="eyebrow">Your journey</div><h2>Past days</h2></div><button className="icon-button" onClick={onClose}>×</button></div>{history.length === 0 ? <p>No completed days yet. Your first decision will appear here after Day 1.</p> : <div className="history-list">{history.map(item => <article className="history-item" key={item.id}><div className="history-day">DAY {item.day}</div><h3>{decisionName(item.payload.decision)}</h3>{item.payload.resolvedEventTitle && <p className="history-event">Event: {item.payload.resolvedEventTitle}</p>}<div className="history-stats"><span>Revenue <strong>{formatINR(item.payload.revenue ?? 0)}</strong></span><span>Profit <strong className={(item.payload.profit ?? 0) >= 0 ? "positive" : "negative"}>{formatINR(item.payload.profit ?? 0)}</strong></span><span>Customers <strong>{item.payload.customers ?? 0}</strong></span><span>Cash <strong>{formatINR(item.payload.cash ?? 0)}</strong></span><span>Reputation <strong>{item.payload.reputation ?? 0}</strong></span></div><p className="history-note">See how this decision affected your business, then use that lesson on a future day.</p></article>)}</div>}</Modal>; 
