"use client";

import { useEffect, useMemo, useState } from "react";
import { CAPITAL_OPTIONS, FORMAT_OPTIONS, LOCATION_OPTIONS, MENU_ITEMS, formatINR, type BusinessFormat, type Decision, type GameState, type Location, type MenuItemId } from "@/lib/simulation";

const decisionLabels: Array<[Decision, string, string]> = [["raise-price", "Raise prices", "Increase average ticket, but demand may soften."], ["marketing", "Run marketing", "Spend ₹10,000 to attract more customers."], ["hire", "Hire staff", "Spend ₹18,000 to improve service capacity."], ["quality", "Improve quality", "Spend ₹12,000 on product and experience."], ["inventory", "Restock", "Spend ₹8,000 to protect against stockouts."]];

export default function Home() {
  const [state, setState] = useState<GameState | null>(null), [selected, setSelected] = useState<Decision | null>(null), [eventOption, setEventOption] = useState<string | null>(null), [feedbackOpen, setFeedbackOpen] = useState(false), [feedbackSent, setFeedbackSent] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { fetch("/api/game/session").then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to start game."); setState(d.state as GameState); }).catch((e: Error) => setError(e.message)); }, []);
  const newBusiness = async () => { if (!confirm("Start a new business? Your current run will remain saved, but this browser will switch to the new run.")) return; setBusy(true); const r = await fetch("/api/game/new", { method: "POST" }); const d = await r.json(); setBusy(false); if (!r.ok) { setError(d.error || "Unable to start a new business."); return; } setState(d.state as GameState); setSelected(null); setEventOption(null); setError(""); };
  const endDay = async () => { if (!state || !selected || (state.currentEvent && !eventOption)) return; setBusy(true); setError(""); try { const r = await fetch("/api/simulate-turn", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision: selected, eventOption }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to advance simulation."); setState(d.state as GameState); setSelected(null); setEventOption(null); } catch (e) { setError(e instanceof Error ? e.message : "Unable to advance simulation."); } finally { setBusy(false); } };
  const submitFeedback = async (rating: number) => { if (!state) return; const r = await fetch("/api/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, replay: rating >= 4, realism: 3, difficulty: 3, sessionDays: state.day }) }); if (r.ok) setFeedbackSent(true); };
  if (!state) return <main className="shell"><div className="container"><section className="hero"><div className="badge">BUSINESS SIMULATOR • PROTOTYPE</div><h1>Starting your Mumbai café…</h1><p>{error || "Creating a secure server-side game session."}</p>{error && <button className="primary" onClick={() => window.location.reload()}>Try again</button>}</section></div></main>;
  if (!state.setupComplete) return <SetupScreen onComplete={setState} />;
  const statusText = state.cash <= 0 ? "Bankrupt" : state.day >= 91 && state.profit > 0 ? "Business survived 90 days" : "Active business";
  return <main className="shell"><div className="container"><div className="topbar"><div className="brand">Business Simulator</div><div className="top-actions"><div className="badge">Mumbai • Café • {statusText}</div><button className="action compact" onClick={newBusiness} disabled={busy}>New business</button></div></div>
    <section className="hero"><div className="badge">DAY {state.day}</div><h1>Run the business. Make the call.</h1><p>One decision at a time. The simulation engine owns the numbers; AI is reserved for high-value scenarios.</p>{error && <div className="notice">{error}</div>}</section>
    <section className="grid metrics"><Metric label="Cash" value={formatINR(state.cash)} /><Metric label="Today's revenue" value={formatINR(state.revenue)} /><Metric label="Today's profit" value={formatINR(state.profit)} good={state.profit >= 0} /><Metric label="Customers" value={state.customers.toLocaleString("en-IN")} /><Metric label="Reputation" value={`${state.reputation}/100`} /></section>
    {state.currentEvent && <section className="panel event-panel"><div className="badge">BUSINESS EVENT</div><h2 className="section-title">{state.currentEvent.title}</h2><p>{state.currentEvent.narrative}</p><div className="actions">{state.currentEvent.options.map(o => <button key={o.id} className={`action ${eventOption === o.id ? "selected" : ""}`} onClick={() => setEventOption(o.id)} disabled={busy}><strong>{eventOption === o.id ? "✓ " : ""}{o.title}</strong><small>{o.description}{o.cost ? ` • Cost ${formatINR(o.cost)}` : ""}</small></button>)}</div><div className="notice">The simulator evaluates this decision from the actual business state. AI does not decide the numerical outcome.</div></section>}
    <div className="grid main-grid"><section className="panel"><h2 className="section-title">What will you do today?</h2><div className="actions">{decisionLabels.map(([id, title, description]) => <button key={id} className={`action ${selected === id ? "selected" : ""}`} onClick={() => setSelected(id)} disabled={busy}><strong>{selected === id ? "✓ " : ""}{title}</strong><small>{description}</small></button>)}</div><div className="notice">Selected action: <strong>{selected ? decisionLabels.find(([id]) => id === selected)?.[1] : "none"}</strong></div><button className="primary" onClick={endDay} disabled={busy || !selected || !!(state.currentEvent && !eventOption)}>{busy ? "Processing…" : "End day →"}</button></section>
      <section className="panel"><h2 className="section-title">Your business</h2><div className="market"><div className="market-row"><span>Location</span><strong>{LOCATION_OPTIONS.find(x => x.id === state.location)?.name}</strong></div><div className="market-row"><span>Format</span><strong>{FORMAT_OPTIONS.find(x => x.id === state.format)?.name}</strong></div><div className="market-row"><span>Service capacity</span><strong>{state.serviceCapacity}/day</strong></div><div className="market-row"><span>Staff</span><strong>{state.staff}/100</strong></div><div className="market-row"><span>Quality</span><strong>{state.quality}/100</strong></div><div className="market-row"><span>Inventory</span><strong>{state.inventory}/100</strong></div></div><div className="notice">Menu: {state.menu.map(id => MENU_ITEMS.find(x => x.id === id)?.name).join(" • ")}</div></section></div>
    <div className="grid main-grid"><section className="panel"><h2 className="section-title">Startup economics</h2><div className="market"><div className="market-row"><span>Starting capital</span><strong>{formatINR(state.capital)}</strong></div><div className="market-row"><span>Setup investment</span><strong>{formatINR(state.setupCost)}</strong></div><div className="market-row"><span>Opening cash reserve</span><strong>{formatINR(state.cash)}</strong></div><div className="market-row"><span>Monthly rent</span><strong>{formatINR(LOCATION_OPTIONS.find(x => x.id === state.location)?.rentMonthly ?? 0)}</strong></div></div></section><section className="panel"><h2 className="section-title">Run feedback</h2><p>Help us tune the simulator. A rating is enough; no long survey.</p>{!feedbackOpen ? <button className="primary" onClick={() => setFeedbackOpen(true)}>Rate this run</button> : feedbackSent ? <div className="notice">Thanks. Your feedback has been recorded.</div> : <div className="actions">{[1,2,3,4,5].map(r => <button key={r} className="action" onClick={() => submitFeedback(r)}><strong>{r}/5</strong></button>)}</div>}</section></div>
    <div className="footer">Prototype v0.3 • Server-authoritative simulation • Fast decision loop • AI used selectively.</div></div></main>;
}

function SetupScreen({ onComplete }: { onComplete: (state: GameState) => void }) {
  const [capital, setCapital] = useState(1000000), [location, setLocation] = useState<Location>("high-footfall"), [format, setFormat] = useState<BusinessFormat>("small-cafe"), [menu, setMenu] = useState<MenuItemId[]>(["filter-coffee", "masala-chai"]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const selectedFormat = FORMAT_OPTIONS.find(x => x.id === format)!; const menuCost = useMemo(() => menu.reduce((sum, id) => sum + (MENU_ITEMS.find(x => x.id === id)?.setupCost ?? 0), 0), [menu]); const setupCost = selectedFormat.cost + menuCost + 50000 + Math.max(30000, menu.length * 15000); const reserve = capital - setupCost;
  const supports = (itemId: MenuItemId) => { const item = MENU_ITEMS.find(x => x.id === itemId)!; if (item.infrastructure === "kitchen") return format === "full-cafe"; if (item.infrastructure === "beverage") return format !== "takeaway"; return true; };
  const lockedReason = (itemId: MenuItemId) => { const item = MENU_ITEMS.find(x => x.id === itemId)!; if (item.infrastructure === "kitchen" && format !== "full-cafe") return "Requires full-service kitchen"; if (item.infrastructure === "beverage" && format === "takeaway") return "Requires beverage equipment"; return ""; };
  const toggleMenu = (id: MenuItemId) => { if (!supports(id)) return; setMenu(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]); };
  useEffect(() => { setMenu(current => current.filter(supports)); }, [format]);
  const launch = async () => { setBusy(true); setError(""); try { const r = await fetch("/api/game/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ capital, location, format, menu }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to configure business."); onComplete(d.state as GameState); } catch (e) { setError(e instanceof Error ? e.message : "Unable to configure business."); } finally { setBusy(false); } };
  return <main className="shell"><div className="container setup-container"><section className="hero setup-hero"><div className="badge">BUSINESS SETUP • DAY 0</div><h1>Build your café before you open it.</h1><p>Choose your total starting budget, lease type, business format and menu. Every choice changes what you can afford later.</p></section>
    <section className="panel setup-section"><div className="step-heading"><span>1</span><div><h2 className="section-title">Starting capital</h2><p className="step-help">This is the total cash available to start the business. Setup costs come out of this amount; the remainder becomes your working capital.</p></div></div><div className="actions capital-grid">{CAPITAL_OPTIONS.map(v => <button key={v} className={`action ${capital === v ? "selected" : ""}`} onClick={() => setCapital(v)}><strong>{capital === v ? "✓ " : ""}{formatINR(v)}</strong><small>Total business budget</small></button>)}</div></section>
    <section className="panel setup-section"><div className="step-heading"><span>2</span><div><h2 className="section-title">Choose your location</h2><p className="step-help">Rent is shown per month, but the simulation accounts for it as a daily operating expense.</p></div></div><div className="actions option-grid">{LOCATION_OPTIONS.map(o => <button key={o.id} className={`action ${location === o.id ? "selected" : ""}`} onClick={() => setLocation(o.id)}><strong>{location === o.id ? "✓ " : ""}{o.name}</strong><small>{o.description}</small><em>{formatINR(o.rentMonthly)}/month</em></button>)}</div></section>
    <section className="panel setup-section"><div className="step-heading"><span>3</span><div><h2 className="section-title">Choose your business format</h2><p className="step-help">Your format determines the space, capacity and infrastructure available for your menu.</p></div></div><div className="actions option-grid">{FORMAT_OPTIONS.map(o => <button key={o.id} className={`action ${format === o.id ? "selected" : ""}`} onClick={() => setFormat(o.id)}><strong>{format === o.id ? "✓ " : ""}{o.name}</strong><small>{o.description}</small><em>Setup {formatINR(o.cost)} • Capacity {o.capacity}/day</em></button>)}</div></section>
    <section className="panel setup-section"><div className="step-heading"><span>4</span><div><h2 className="section-title">Build your menu</h2><p className="step-help">Only menu items your chosen format can physically support are selectable. Each item has its own setup and ongoing operating cost.</p></div></div><div className="actions menu-grid">{MENU_ITEMS.map(item => { const available = supports(item.id); const selected = menu.includes(item.id); return <button key={item.id} className={`action ${selected ? "selected" : ""} ${!available ? "locked" : ""}`} onClick={() => toggleMenu(item.id)} disabled={!available}><strong>{selected ? "✓ " : !available ? "🔒 " : ""}{item.name}</strong><small>{available ? `Setup ${formatINR(item.setupCost)} • Weekly operating cost ${formatINR(item.weeklyCost)}` : lockedReason(item.id)}</small><em>{item.infrastructure} infrastructure</em></button>; })}</div></section>
    <section className="panel setup-section"><div className="step-heading"><span>5</span><div><h2 className="section-title">Review before opening</h2><p className="step-help">This is the point of no return for the setup. Your remaining cash is what you have to survive the early days.</p></div></div><div className="review-grid"><div><span>Starting capital</span><strong>{formatINR(capital)}</strong></div><div><span>Setup investment</span><strong>{formatINR(setupCost)}</strong></div><div><span>Cash after setup</span><strong>{formatINR(reserve)}</strong></div><div><span>Monthly rent</span><strong>{formatINR(LOCATION_OPTIONS.find(x => x.id === location)?.rentMonthly ?? 0)}</strong></div></div>{error && <div className="notice">{error}</div>}<button className="primary" onClick={launch} disabled={busy || reserve <= 0 || menu.length === 0}>{busy ? "Opening…" : `Open ${selectedFormat.name} →`}</button></section>
  </div></main>;
}
function Metric({ label, value, good }: { label: string; value: string; good?: boolean }) { return <div className="panel"><div className="metric-label">{label}</div><div className={`metric-value ${good ? "good" : ""}`}>{value}</div></div>; }
