export type Location = "high-footfall" | "residential" | "premium";
export type BusinessFormat = "takeaway" | "small-cafe" | "full-cafe";
export type Infrastructure = "basic" | "beverage" | "kitchen";
export type MenuItemId = "filter-coffee" | "instant-coffee" | "masala-chai" | "lemon-tea" | "bun-maska" | "butter-toast" | "samosa" | "vada-pav" | "veg-sandwich" | "poha-upma" | "espresso" | "cappuccino" | "cold-coffee" | "milkshake" | "grilled-sandwich" | "fries" | "pasta" | "rice-meal" | "biryani" | "paneer-main" | "dessert";
export type MenuItem = { id: MenuItemId; name: string; setupCost: number; weeklyCost: number; ticketImpact: number; demandImpact: number; infrastructure: Infrastructure };
export const MENU_ITEMS: MenuItem[] = [
  { id: "filter-coffee", name: "Filter Coffee", setupCost: 20000, weeklyCost: 5000, ticketImpact: 10, demandImpact: 4, infrastructure: "basic" },
  { id: "instant-coffee", name: "Instant Coffee", setupCost: 10000, weeklyCost: 4500, ticketImpact: 5, demandImpact: 4, infrastructure: "basic" },
  { id: "masala-chai", name: "Masala Chai", setupCost: 12000, weeklyCost: 3500, ticketImpact: 8, demandImpact: 5, infrastructure: "basic" },
  { id: "lemon-tea", name: "Lemon / Ginger Tea", setupCost: 10000, weeklyCost: 3000, ticketImpact: 5, demandImpact: 3, infrastructure: "basic" },
  { id: "bun-maska", name: "Bun Maska", setupCost: 15000, weeklyCost: 4000, ticketImpact: 20, demandImpact: 6, infrastructure: "basic" },
  { id: "butter-toast", name: "Butter / Jam Toast", setupCost: 18000, weeklyCost: 4500, ticketImpact: 25, demandImpact: 5, infrastructure: "basic" },
  { id: "samosa", name: "Samosa", setupCost: 20000, weeklyCost: 5500, ticketImpact: 25, demandImpact: 7, infrastructure: "basic" },
  { id: "vada-pav", name: "Vada Pav", setupCost: 25000, weeklyCost: 6500, ticketImpact: 30, demandImpact: 9, infrastructure: "basic" },
  { id: "veg-sandwich", name: "Simple Veg Sandwich", setupCost: 35000, weeklyCost: 7000, ticketImpact: 40, demandImpact: 8, infrastructure: "basic" },
  { id: "poha-upma", name: "Poha / Upma", setupCost: 30000, weeklyCost: 6000, ticketImpact: 30, demandImpact: 6, infrastructure: "basic" },
  { id: "espresso", name: "Espresso", setupCost: 75000, weeklyCost: 9000, ticketImpact: 45, demandImpact: 7, infrastructure: "beverage" },
  { id: "cappuccino", name: "Cappuccino / Latte", setupCost: 120000, weeklyCost: 12000, ticketImpact: 85, demandImpact: 10, infrastructure: "beverage" },
  { id: "cold-coffee", name: "Cold Coffee", setupCost: 60000, weeklyCost: 8000, ticketImpact: 65, demandImpact: 9, infrastructure: "beverage" },
  { id: "milkshake", name: "Milkshakes", setupCost: 70000, weeklyCost: 9000, ticketImpact: 75, demandImpact: 8, infrastructure: "beverage" },
  { id: "grilled-sandwich", name: "Grilled / Club Sandwich", setupCost: 90000, weeklyCost: 10000, ticketImpact: 90, demandImpact: 10, infrastructure: "kitchen" },
  { id: "fries", name: "Fries / Loaded Fries", setupCost: 70000, weeklyCost: 8500, ticketImpact: 70, demandImpact: 8, infrastructure: "kitchen" },
  { id: "pasta", name: "Pasta / Noodles", setupCost: 110000, weeklyCost: 11000, ticketImpact: 100, demandImpact: 9, infrastructure: "kitchen" },
  { id: "rice-meal", name: "Rice & Curry Meal", setupCost: 120000, weeklyCost: 13000, ticketImpact: 120, demandImpact: 8, infrastructure: "kitchen" },
  { id: "biryani", name: "Biryani", setupCost: 140000, weeklyCost: 15000, ticketImpact: 150, demandImpact: 10, infrastructure: "kitchen" },
  { id: "paneer-main", name: "Paneer / Chicken Main", setupCost: 150000, weeklyCost: 16000, ticketImpact: 160, demandImpact: 9, infrastructure: "kitchen" },
  { id: "dessert", name: "Desserts", setupCost: 80000, weeklyCost: 9000, ticketImpact: 80, demandImpact: 6, infrastructure: "kitchen" },
];
export type GameEventId = "bad-review" | "supplier-increase" | "staff-absence" | "rain" | "competitor-promotion" | "local-event" | "equipment-issue" | "viral-mention" | "bulk-order" | "stock-shortage";
export type GameEvent = { id: GameEventId; title: string; narrative: string; severity: 1 | 2 | 3; options: Array<{ id: string; title: string; description: string; cost: number }> };
export type Decision = "raise-price" | "lower-price" | "marketing" | "hire" | "quality" | "inventory" | "inventory-2" | "inventory-3" | "no-action" | "supply-contract" | "hire-manager" | "extend-hours" | "loyalty-programme";
export type DayRecord = { day: number; decision: Decision; eventId: GameEventId | null; eventOption: string | null; cashBefore: number; cashAfter: number; revenue: number; profit: number; customers: number; reputation: number; priceIndex: number; inventory: number; wastage: number };
export type GameState = { version: 4; setupComplete: boolean; businessName: string; day: number; cash: number; revenue: number; profit: number; customers: number; totalCustomers: number; cumulativeRevenue: number; cumulativeProfit: number; reputation: number; priceIndex: number; marketing: number; staff: number; quality: number; inventory: number; wastageToday: number; location: Location; capital: number; format: BusinessFormat; menu: MenuItemId[]; setupCost: number; serviceCapacity: number; currentEvent: GameEvent | null; eventHistory: string[]; dayHistory: DayRecord[]; consecutivePriceRaises: number; priceChangesLast7: number; profitableDays: number; lossDays: number; profitStreak: number; lossStreak: number; supplierCostMultiplier: number; supplyContract: boolean; manager: boolean; extendedHours: boolean; loyalty: boolean; lastEventDay: number; milestones: string[]; lastDayMessage: string; seed: number };
export const CAPITAL_OPTIONS = [500000, 1000000, 2000000, 3500000, 5000000];
export const LOCATION_OPTIONS: Array<{ id: Location; name: string; rentMonthly: number; demand: number; description: string }> = [
  { id: "high-footfall", name: "High-footfall", rentMonthly: 100000, demand: 1.2, description: "Higher demand and visibility, but the highest volume pressure." },
  { id: "residential", name: "Residential", rentMonthly: 80000, demand: 0.9, description: "Lower rent with steadier repeat neighbourhood demand." },
  { id: "premium", name: "Premium district", rentMonthly: 175000, demand: 1.0, description: "Highest rent, but stronger premium pricing potential." },
];
export const FORMAT_OPTIONS: Array<{ id: BusinessFormat; name: string; cost: number; staff: number; capacity: number; description: string }> = [
  { id: "takeaway", name: "Takeaway kiosk", cost: 120000, staff: 55, capacity: 120, description: "Small footprint with a quick-service menu: tea, coffee, buns and simple snacks." },
  { id: "small-cafe", name: "Small café", cost: 250000, staff: 65, capacity: 200, description: "Seating plus beverage equipment and a broader café menu." },
  { id: "full-cafe", name: "Full-service restaurant", cost: 450000, staff: 72, capacity: 300, description: "Full seating and kitchen infrastructure for a broad food menu." },
];
export const INITIAL_STATE: GameState = { version: 4, setupComplete: false, businessName: "", day: 1, cash: 0, revenue: 0, profit: 0, customers: 0, totalCustomers: 0, cumulativeRevenue: 0, cumulativeProfit: 0, reputation: 50, priceIndex: 100, marketing: 25, staff: 0, quality: 65, inventory: 75, wastageToday: 0, location: "high-footfall", capital: 0, format: "small-cafe", menu: [], setupCost: 0, serviceCapacity: 0, currentEvent: null, eventHistory: [], dayHistory: [], consecutivePriceRaises: 0, priceChangesLast7: 0, profitableDays: 0, lossDays: 0, profitStreak: 0, lossStreak: 0, supplierCostMultiplier: 1, supplyContract: false, manager: false, extendedHours: false, loyalty: false, lastEventDay: 0, milestones: [], lastDayMessage: "", seed: 0 };
export function upgradeLegacyState(raw: Partial<GameState>): GameState {
  if (raw.version === 4 && typeof raw.wastageToday === "number" && typeof raw.seed === "number") return raw as GameState;
  return { ...INITIAL_STATE, ...raw, version: 4, setupComplete: raw.setupComplete ?? true, businessName: raw.businessName ?? "", capital: Number(raw.capital ?? raw.cash ?? 500000), format: raw.format ?? "small-cafe", menu: raw.menu?.length ? raw.menu : ["filter-coffee", "instant-coffee", "masala-chai", "bun-maska", "vada-pav", "veg-sandwich"], setupCost: Number(raw.setupCost ?? 0), serviceCapacity: Number(raw.serviceCapacity ?? 200), currentEvent: raw.currentEvent ?? null, eventHistory: raw.eventHistory ?? [], dayHistory: (raw.dayHistory ?? []).map(record => ({ ...record, inventory: Number((record as Partial<DayRecord>).inventory ?? 0), wastage: Number((record as Partial<DayRecord>).wastage ?? 0) })), totalCustomers: Number(raw.totalCustomers ?? raw.customers ?? 0), cumulativeRevenue: Number(raw.cumulativeRevenue ?? raw.revenue ?? 0), cumulativeProfit: Number(raw.cumulativeProfit ?? raw.profit ?? 0), inventory: Math.max(0, Math.min(100, Number(raw.inventory ?? 75))), wastageToday: Number(raw.wastageToday ?? 0), consecutivePriceRaises: Number(raw.consecutivePriceRaises ?? 0), priceChangesLast7: Number(raw.priceChangesLast7 ?? 0), profitableDays: Number(raw.profitableDays ?? 0), lossDays: Number(raw.lossDays ?? 0), profitStreak: Number(raw.profitStreak ?? 0), lossStreak: Number(raw.lossStreak ?? 0), supplierCostMultiplier: Number(raw.supplierCostMultiplier ?? 1), supplyContract: Boolean(raw.supplyContract), manager: Boolean(raw.manager), extendedHours: Boolean(raw.extendedHours), loyalty: Boolean(raw.loyalty), lastEventDay: Number(raw.lastEventDay ?? 0), milestones: raw.milestones ?? [], lastDayMessage: raw.lastDayMessage ?? "", seed: Number(raw.seed ?? Math.floor(Math.random() * 2147483647)) };
}
export function formatINR(value: number): string { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }
export function calculateSetup(capital: number, location: Location, format: BusinessFormat, menu: MenuItemId[]) {
  const formatOption = FORMAT_OPTIONS.find(x => x.id === format); const locationOption = LOCATION_OPTIONS.find(x => x.id === location); if (!formatOption || !locationOption) throw new Error("Invalid business configuration.");
  const selected = menu.map(id => MENU_ITEMS.find(x => x.id === id)).filter(Boolean) as MenuItem[]; if (selected.length !== menu.length) throw new Error("Invalid menu item.");
  if (selected.some(item => item.infrastructure === "beverage") && format === "takeaway") throw new Error("Specialty drinks require a small café or full-service restaurant."); if (selected.some(item => item.infrastructure === "kitchen") && format !== "full-cafe") throw new Error("Kitchen menu items require a full-service restaurant.");
  const menuCost = selected.reduce((sum, item) => sum + item.setupCost, 0); const licensing = 50000; const openingInventory = Math.max(30000, menu.length * 15000); const setupCost = formatOption.cost + menuCost + licensing + openingInventory;
  return { setupCost, reserve: capital - setupCost, staff: formatOption.staff, serviceCapacity: formatOption.capacity, rentMonthly: locationOption.rentMonthly };
}
export function createConfiguredState(input: { capital: number; location: Location; format: BusinessFormat; menu: MenuItemId[]; businessName?: string }): GameState {
  if (!CAPITAL_OPTIONS.includes(input.capital)) throw new Error("Invalid capital."); if (!input.menu.length) throw new Error("Choose at least one menu item."); const result = calculateSetup(input.capital, input.location, input.format, input.menu); if (result.reserve <= 0) throw new Error("Startup configuration exceeds available capital.");
  return { ...INITIAL_STATE, setupComplete: true, businessName: (input.businessName ?? "").trim().slice(0, 40), capital: input.capital, cash: result.reserve, location: input.location, format: input.format, menu: input.menu, setupCost: result.setupCost, staff: result.staff, serviceCapacity: result.serviceCapacity, inventory: 75, milestones: ["open-business"], seed: Math.floor(Math.random() * 2147483647) };
}
function menuStats(menu: MenuItem[]) { return menu.reduce((acc, item) => ({ ticket: acc.ticket + item.ticketImpact, demand: acc.demand + item.demandImpact, weeklyCost: acc.weeklyCost + item.weeklyCost }), { ticket: 0, demand: 0, weeklyCost: 0 }); }
export function getAvailableDecisions(state: GameState): Decision[] {
  let decisions: Decision[]; if (state.day === 1) decisions = ["marketing", "hire", "inventory", "inventory-2", "inventory-3", "no-action"]; else if (state.day === 2) decisions = ["marketing", "hire", "quality", "inventory", "inventory-2", "inventory-3", "no-action"]; else decisions = ["raise-price", "lower-price", "marketing", "hire", "quality", "inventory", "inventory-2", "inventory-3", "no-action"];
  // Strategic moves become available once the business is past its first three months.
  if (state.day > 90) {
    if (!state.supplyContract) decisions.push("supply-contract");
    if (!state.manager) decisions.push("hire-manager");
    if (!state.extendedHours) decisions.push("extend-hours");
    if (!state.loyalty) decisions.push("loyalty-programme");
  }
  return decisions.filter(decision => { if (decision === "raise-price" && state.priceIndex >= 140) return false; if (decision === "lower-price" && state.priceIndex <= 100) return false; if (decision.startsWith("inventory") && state.inventory >= 100) return false; if (decision === "quality" && state.quality >= 100) return false; if (decision === "marketing" && state.marketing >= 100) return false; if (decision === "hire" && state.staff >= 100 && state.serviceCapacity >= 600) return false; return decision === "no-action" || decision === "raise-price" || decision === "lower-price" || state.cash >= getDecisionCost(decision); });
}
export function getDecisionCost(decision: Decision): number { return { "raise-price": 0, "lower-price": 0, marketing: 10000, hire: 18000, quality: 12000, inventory: 8000, "inventory-2": 15000, "inventory-3": 21000, "no-action": 0, "supply-contract": 35000, "hire-manager": 45000, "extend-hours": 22000, "loyalty-programme": 30000 }[decision]; }
export function isDecisionAvailable(state: GameState, decision: Decision): boolean { return getAvailableDecisions(state).includes(decision); }
export function applyDecision(state: GameState, decision: Decision): GameState {
  if (!isDecisionAvailable(state, decision)) return state; const next = { ...state };
  switch (decision) { case "raise-price": next.priceIndex = Math.min(140, next.priceIndex + 6); next.consecutivePriceRaises += 1; next.priceChangesLast7 += 1; break; case "lower-price": next.priceIndex = Math.max(100, next.priceIndex - 6); next.consecutivePriceRaises = 0; next.priceChangesLast7 += 1; break; case "marketing": next.cash -= 10000; next.marketing = Math.min(100, next.marketing + 14); break; case "hire": next.cash -= 18000; next.staff = Math.min(100, next.staff + 10); next.serviceCapacity = Math.min(next.serviceCapacity + 15, 600); break; case "quality": next.cash -= 12000; next.quality = Math.min(100, next.quality + 7); break; case "inventory": next.cash -= 8000; next.inventory = Math.min(100, next.inventory + 30); break; case "inventory-2": next.cash -= 15000; next.inventory = Math.min(100, next.inventory + 60); break; case "inventory-3": next.cash -= 21000; next.inventory = Math.min(100, next.inventory + 90); break; case "supply-contract": next.cash -= 35000; next.supplyContract = true; break;
    case "hire-manager": next.cash -= 45000; next.manager = true; next.staff = Math.min(100, next.staff + 8); break;
    case "extend-hours": next.cash -= 22000; next.extendedHours = true; next.serviceCapacity = Math.min(600, next.serviceCapacity + 40); break;
    case "loyalty-programme": next.cash -= 30000; next.loyalty = true; break;
    case "no-action": break; }
  if (decision !== "raise-price") next.consecutivePriceRaises = 0; return next;
}
function seededNoise(seed: number, day: number): number { let x = (seed ^ Math.imul(day + 0x9e3779b9, 0x85ebca6b)) >>> 0; x ^= x >>> 16; x = Math.imul(x, 0x7feb352d) >>> 0; x ^= x >>> 15; x = Math.imul(x, 0x846ca68b) >>> 0; x ^= x >>> 16; return 0.85 + (x / 4294967296) * 0.30; }
function priceDemandFactor(state: GameState): number { const tolerance = state.location === "premium" ? 0.10 : state.location === "high-footfall" ? 0.03 : 0; const baseIncrease = Math.max(0, state.priceIndex - 100) / 100; let elasticity = 1 - Math.min(0.52, baseIncrease * (1.20 - tolerance)); if (state.consecutivePriceRaises >= 2) elasticity -= Math.min(0.20, (state.consecutivePriceRaises - 1) * 0.065); if (state.consecutivePriceRaises >= 4) elasticity -= 0.07; return Math.max(0.28, elasticity); }
function serviceFactor(state: GameState): number { const targetStaff = state.format === "takeaway" ? 55 : state.format === "small-cafe" ? 65 : 72; return Math.min(1.08, 0.84 + state.staff / Math.max(1, targetStaff) * 0.16); }
function addMilestones(state: GameState, previousProfit: number): string[] { const unlocked = new Set(state.milestones); const add = (id: string, condition: boolean) => { if (condition) unlocked.add(id); }; add("first-sale", state.cumulativeRevenue > 0); add("first-customer", state.totalCustomers >= 1); add("100-customers", state.totalCustomers >= 100); add("500-customers", state.totalCustomers >= 500); add("1000-customers", state.totalCustomers >= 1000); add("revenue-1l", state.cumulativeRevenue >= 100000); add("revenue-5l", state.cumulativeRevenue >= 500000); add("revenue-10l", state.cumulativeRevenue >= 1000000); add("first-profit", state.profitableDays >= 1); add("profit-streak-3", state.profitStreak >= 3); add("profit-streak-5", state.profitStreak >= 5); add("crisis-survived", state.eventHistory.length >= 1 && state.cash > 0); add("bounce-back", previousProfit < 0 && state.profit > 0); add("reputation-60", state.reputation >= 60); add("reputation-80", state.reputation >= 80); add("day-5", state.day > 5); add("day-10", state.day > 10); add("day-30", state.day > 30); return [...unlocked]; }
function dayMessage(state: GameState, decision: Decision, previous: GameState): string { const profitDelta = state.profit - previous.profit; if (state.wastageToday > 2000) return "You're carrying too much stock. 📦 Some of it went to waste today — cash can't earn anything while it's sitting on the shelf."; if (state.inventory < 20) return "Careful — the shelves are getting bare. One more busy day could mean lost sales."; if (state.profitStreak >= 3) return "Now we're cooking. 🔥 Three good days in a row. Enjoy the win — tomorrow still has a vote."; if (state.profit < 0 && state.lossStreak >= 2) return "Oof. The business is feeling it. Take a breath — one smart move can change the direction."; if (decision === "raise-price" && state.consecutivePriceRaises >= 3) return "Your customers noticed. 💸 The extra margin came with a cost. Maybe give the prices a little breathing room."; if (decision === "lower-price" && state.profit > previous.profit) return "A little breathing room helped. Lower prices can recover demand when you've pushed too far."; if (decision === "raise-price" && state.profit > previous.profit) return "That price move paid off. ☕ Just remember: what works today may not work three days in a row."; if (decision === "no-action" && state.profit > 0) return "A steady day. 📈 Sometimes the smartest move is not to fix what isn't broken."; if (decision === "no-action" && state.profit < 0) return "You held steady today. That's useful information — now watch what the business is telling you."; if (state.profit > 0 && profitDelta > 0) return "Today paid off. 📈 Your business moved in the right direction. Enjoy this one."; if (state.profit > 0) return "A solid day. Nothing flashy — just a business doing its job."; if (state.profit < 0 && previous.profit >= 0) return "Careful. Costs are catching up. A rough day is information, not a verdict."; if (state.reputation > previous.reputation) return "People seem to like what you're doing. ⭐ Keep that feeling going."; if (state.reputation < previous.reputation) return "The customers have opinions. 😬 Watch what changed today before making the next move."; return "Another day in the books. Sometimes boring is profitable. Tomorrow, we try again."; }
export function advanceDay(state: GameState, decision: Decision = "marketing", turnSpend = 0, rainToday = false, resolvedEventId: GameEventId | null = null, resolvedEventOption: string | null = null): GameState {
  const location = LOCATION_OPTIONS.find(x => x.id === state.location)!; const items = state.menu.map(id => MENU_ITEMS.find(x => x.id === id)).filter(Boolean) as MenuItem[]; const menu = menuStats(items); const priceFactor = priceDemandFactor(state); const qualityFactor = 0.68 + state.quality / 230; const reputationFactor = 0.55 + state.reputation / 200 + (state.loyalty ? 0.06 : 0); const marketingFactor = 1 + state.marketing / 360; const menuFactor = Math.min(1.80, 0.88 + menu.demand / 85); const service = serviceFactor(state) * (state.extendedHours ? 1.10 : 1) * (state.manager ? 1.04 : 1); const marketNoise = seededNoise(state.seed, state.day); const rainPenalty = rainToday ? 0.88 : 1; const stockPenalty = state.inventory < 15 ? 0.68 : state.inventory < 30 ? 0.82 : state.inventory < 45 ? 0.92 : 1;
  const demand = location.demand * priceFactor * qualityFactor * reputationFactor * marketingFactor * menuFactor * service * marketNoise * rainPenalty * stockPenalty; const demandCustomers = Math.max(0, Math.min(state.serviceCapacity, Math.round(105 * demand))); const customers = Math.min(demandCustomers, Math.max(0, Math.floor(state.inventory * 9))); const averageTicket = Math.round((280 + 35 * Math.sqrt(Math.max(0, menu.ticket) / 10)) * (state.priceIndex / 100)); const revenue = customers * averageTicket;
  const rent = Math.round(location.rentMonthly / 30); const payroll = 7000 + Math.round(state.staff * 60) + (state.manager ? 2600 : 0) + (state.extendedHours ? 1900 : 0) + (state.loyalty ? 700 : 0); const cogs = Math.round(revenue * (0.27 + (state.supplierCostMultiplier - 1) * 0.45 + (state.supplyContract ? 0.035 : 0))); const marketingSpend = Math.round(Math.max(0, state.marketing - 25) * 85); const menuOperatingCost = Math.round(menu.weeklyCost / 7); const capacityStress = customers >= state.serviceCapacity * 0.9 ? 3500 : customers >= state.serviceCapacity * 0.78 ? 1200 : 0; const stockUsed = customers > 0 ? Math.max(4, Math.round(customers / 9)) : 0; const wastage = state.inventory > 82 ? Math.round((state.inventory - 82) * 180) : 0; const stockoutCost = state.inventory - stockUsed < 0 ? Math.round(Math.abs(state.inventory - stockUsed) * 250) : 0; const serviceQualityPenalty = customers >= state.serviceCapacity * 0.98 ? 2 : customers >= state.serviceCapacity * 0.9 ? 1 : 0; const operatingCost = rent + payroll + cogs + marketingSpend + menuOperatingCost + capacityStress + wastage + stockoutCost; const profit = revenue - operatingCost - turnSpend;
  const closedToday = customers === 0 && state.serviceCapacity > 0;
  // Reputation cannot float far above the quality actually being delivered.
  const reputationCeiling = Math.max(10, Math.min(100, state.quality + 22));
  const overCeiling = Math.max(0, state.reputation - reputationCeiling);
  let reputationChange = (profit > 0 ? 0.45 : -0.5)
    + (state.quality >= 75 ? 0.3 : 0)
    - (state.quality < 50 ? 0.5 : 0)
    - (state.manager ? serviceQualityPenalty * 0.5 : serviceQualityPenalty)
    - (state.consecutivePriceRaises >= 3 ? 1.0 : state.consecutivePriceRaises === 2 ? 0.45 : 0)
    - (state.inventory - stockUsed < 0 ? 1.2 : 0)
    - (state.inventory < 20 ? 0.8 : 0)
    + (wastage > 2000 ? -0.35 : 0);
  // A cafe that served nobody was effectively shut. Word travels fast.
  if (closedToday) reputationChange = Math.min(reputationChange, 0) - 3.2;
  // Drift back down toward what the quality can support.
  if (overCeiling > 0) reputationChange -= Math.min(2.5, overCeiling * 0.35);
  // Gains get harder the higher you already are.
  if (reputationChange > 0 && state.reputation > 80) reputationChange *= 0.45; const previousProfit = state.profit;
  // A supply contract means deliveries arrive without the owner ordering them,
  // but it only covers routine demand and never fully fills the store.
  const restocked = state.supplyContract ? Math.round(stockUsed * 0.92) : 0;
  const nextInventory = Math.max(0, Math.min(state.supplyContract ? 78 : 100, state.inventory - stockUsed + restocked));
  const next: GameState = { ...state, day: state.day + 1, cash: Math.round(state.cash + profit + turnSpend), revenue, profit, customers, totalCustomers: state.totalCustomers + customers, cumulativeRevenue: state.cumulativeRevenue + revenue, cumulativeProfit: state.cumulativeProfit + profit, reputation: Math.max(0, Math.min(100, Math.round((state.reputation + reputationChange) * 10) / 10)), inventory: nextInventory, wastageToday: wastage, marketing: Math.max(25, state.marketing - 3), profitableDays: state.profitableDays + (profit > 0 ? 1 : 0), lossDays: state.lossDays + (profit < 0 ? 1 : 0), profitStreak: profit > 0 ? state.profitStreak + 1 : 0, lossStreak: profit < 0 ? state.lossStreak + 1 : 0, priceChangesLast7: state.day % 7 === 0 ? 0 : state.priceChangesLast7, lastDayMessage: "" };
  next.lastDayMessage = dayMessage(next, decision, state); next.milestones = addMilestones(next, previousProfit); next.dayHistory = [...state.dayHistory, { day: state.day, decision, eventId: resolvedEventId, eventOption: resolvedEventOption, cashBefore: state.cash + turnSpend, cashAfter: next.cash, revenue, profit, customers, reputation: next.reputation, priceIndex: next.priceIndex, inventory: next.inventory, wastage }]; return next;
}
function makeEvent(id: GameEventId, title: string, narrative: string, severity: 1 | 2 | 3, options: GameEvent["options"]): GameEvent { return { id, title, narrative, severity, options }; }
export function generateEvent(state: GameState): GameEvent | null {
  if (state.day < 3 || state.currentEvent || state.day - state.lastEventDay < 2) return null; const candidates: GameEvent[] = [];
  if (state.inventory < 35) candidates.push(makeEvent("stock-shortage", "Stock is running low", "A few popular items may run out before the day is over. You can protect sales now or conserve cash.", 1, [{ id: "emergency-stock", title: "Emergency restock", description: "Pay more for a quick top-up.", cost: 15000 }, { id: "conserve-stock", title: "Conserve stock", description: "Avoid spending, but accept some lost sales.", cost: 0 }]));
  if (state.consecutivePriceRaises >= 2) candidates.push(makeEvent("bad-review", "Customers are noticing the prices", "A regular has posted that the café is getting expensive. How you respond will shape the next few days.", 2, [{ id: "hold-price", title: "Hold prices steady", description: "Give customers a reason to stay while demand settles.", cost: 0 }, { id: "add-value", title: "Add a small value offer", description: "Spend on a simple combo or add-on rather than cutting the headline price.", cost: 12000 }, { id: "ignore-review", title: "Ignore it", description: "Protect margin today and accept the risk.", cost: 0 }]));
  if (state.day % 5 === 0) candidates.push(makeEvent("supplier-increase", "Supplier prices just went up", "Your primary supplier has announced an 18% increase on key ingredients.", 1, [{ id: "accept-supplier", title: "Accept the increase", description: "No disruption, but margins will fall.", cost: 0 }, { id: "switch-supplier", title: "Switch supplier", description: "Pay now to protect margins later.", cost: 12000 }]));
  if (state.day % 4 === 0) candidates.push(makeEvent("rain", "Rain is slowing the street down", "Footfall is expected to be softer today. You can spend to pull customers in or ride it out.", 1, [{ id: "delivery-push", title: "Push a local promotion", description: "Spend on a short promotion to recover some demand.", cost: 9000 }, { id: "ride-it-out", title: "Ride it out", description: "Save cash and accept a quieter day.", cost: 0 }]));
  if (state.day % 6 === 0) candidates.push(makeEvent("competitor-promotion", "A competitor is running a big offer", "The café down the road is attracting attention with an aggressive promotion.", 2, [{ id: "match-offer", title: "Match the offer", description: "Defend demand, but sacrifice some margin.", cost: 14000 }, { id: "differentiate", title: "Lean into quality", description: "Spend on quality and let your reputation do the work.", cost: 12000 }, { id: "ignore-competitor", title: "Ignore it", description: "Keep your strategy and avoid a price war.", cost: 0 }]));
  if (state.day % 9 === 0) candidates.push(makeEvent("local-event", "A local event is bringing people nearby", "A nearby event could create a rush of customers. Are you ready for it?", 1, [{ id: "prepare-staff", title: "Prepare extra staff", description: "Pay for temporary help and capture more of the rush.", cost: 16000 }, { id: "take-the-risk", title: "Take your chances", description: "No cost, but you may struggle with the rush.", cost: 0 }]));
  if (state.day % 11 === 0) candidates.push(makeEvent("equipment-issue", "A piece of equipment is acting up", "One of your key pieces of equipment needs attention before it becomes a bigger problem.", 2, [{ id: "repair-now", title: "Repair it now", description: "Pay now and avoid disruption.", cost: 18000 }, { id: "delay-repair", title: "Delay the repair", description: "Save cash today and accept the risk of downtime.", cost: 0 }]));
  if (state.reputation >= 70 && state.day % 8 === 0) candidates.push(makeEvent("viral-mention", "Someone is talking about your business", "A local food page has mentioned your café. This could bring new customers.", 2, [{ id: "amplify", title: "Amplify the mention", description: "Spend on a small boost while the attention is fresh.", cost: 10000 }, { id: "let-it-spread", title: "Let it spread", description: "No spend. See whether word of mouth carries it.", cost: 0 }]));
  if (state.day % 10 === 0) candidates.push(makeEvent("bulk-order", "A large order opportunity", "A nearby office wants a bulk order. It could be useful revenue, but it will test your capacity.", 2, [{ id: "accept-order", title: "Accept the order", description: "Take the revenue and risk service pressure.", cost: 0 }, { id: "decline-order", title: "Decline politely", description: "Protect the everyday customer experience.", cost: 0 }]));
  if (state.day % 7 === 0) candidates.push(makeEvent("staff-absence", "A staff member is unavailable", "A staffing issue has reduced today's service flexibility.", 2, [{ id: "cover-shift", title: "Cover the shift", description: "Absorb the disruption and protect service.", cost: 0 }, { id: "run-short", title: "Run short", description: "Save cash and accept some pressure.", cost: 0 }]));
  if (!candidates.length) return null; const index = Math.floor((Math.abs(Math.sin((state.seed + state.day) * 7.13)) * 100000) % candidates.length); return candidates[index];
}
export function applyEvent(state: GameState, optionId: string): GameState {
  if (!state.currentEvent) return state; const event = state.currentEvent; const option = event.options.find(item => item.id === optionId); if (!option || state.cash < option.cost) return state;
  const next = { ...state, currentEvent: null, lastEventDay: state.day, eventHistory: [...state.eventHistory, `${state.day}:${event.id}:${optionId}`] }; if (option.cost > 0) next.cash -= option.cost;
  switch (event.id) { case "supplier-increase": if (optionId === "accept-supplier") next.supplierCostMultiplier = Math.min(1.5, next.supplierCostMultiplier + 0.18); break; case "stock-shortage": if (optionId === "emergency-stock") next.inventory = Math.min(100, next.inventory + 35); else if (optionId === "conserve-stock") next.inventory = Math.max(0, next.inventory - 15); break; case "bad-review": if (optionId === "hold-price") { next.consecutivePriceRaises = 0; next.reputation = Math.min(100, next.reputation + 1); } else if (optionId === "add-value") { next.reputation = Math.min(100, next.reputation + 1); next.quality = Math.min(100, next.quality + 2); } else if (optionId === "ignore-review") next.reputation = Math.max(0, next.reputation - 4); break; case "rain": if (optionId === "delivery-push") next.marketing = Math.min(100, next.marketing + 10); break; case "competitor-promotion": if (optionId === "match-offer") next.marketing = Math.min(100, next.marketing + 12); else if (optionId === "differentiate") next.quality = Math.min(100, next.quality + 6); else next.reputation = Math.max(0, next.reputation - 1); break; case "local-event": if (optionId === "prepare-staff") next.serviceCapacity = Math.min(600, next.serviceCapacity + 20); break; case "equipment-issue": if (optionId === "delay-repair") next.quality = Math.max(0, next.quality - 8); break; case "viral-mention": if (optionId === "amplify") next.marketing = Math.min(100, next.marketing + 18); else next.reputation = Math.min(100, next.reputation + 1); break; case "bulk-order": if (optionId === "accept-order") next.serviceCapacity = Math.min(600, next.serviceCapacity + 10); break; case "staff-absence": if (optionId === "cover-shift") next.staff = Math.min(100, next.staff + 3); else next.quality = Math.max(0, next.quality - 4); break; }
  return next;
}

export type StarterPresetId = "steady" | "ambitious" | "lean";
export type StarterPreset = { id: StarterPresetId; name: string; blurb: string; capital: number; location: Location; format: BusinessFormat; menu: MenuItemId[] };
export const STARTER_PRESETS: StarterPreset[] = [
  { id: "steady", name: "Play it safe", blurb: "A small cafe on a residential street. Coffee, chai and snacks. Modest rent, regulars who come back.", capital: 1000000, location: "residential", format: "small-cafe", menu: ["filter-coffee", "masala-chai", "bun-maska", "vada-pav", "veg-sandwich", "espresso"] },
  { id: "ambitious", name: "Go big", blurb: "A full kitchen on a busy high street. Crowds every day, and rent to match.", capital: 2000000, location: "high-footfall", format: "full-cafe", menu: ["filter-coffee", "masala-chai", "cappuccino", "cold-coffee", "veg-sandwich", "grilled-sandwich", "fries", "pasta", "dessert"] },
  { id: "lean", name: "Start tiny", blurb: "A takeaway kiosk. Barely any rent, but nowhere for anyone to sit.", capital: 500000, location: "high-footfall", format: "takeaway", menu: ["filter-coffee", "instant-coffee", "masala-chai", "bun-maska", "vada-pav"] },
];
export function getPreset(id: string): StarterPreset | undefined { return STARTER_PRESETS.find(p => p.id === id); }

/** Short money for tight spaces: ₹30.7L, ₹1.24Cr, ₹8,500. */
export function formatCompactINR(value: number): string {
  const n = Math.round(value);
  const abs = Math.abs(n);
  const sign = n < 0 ? "-" : "";
  if (abs >= 10000000) return `${sign}₹${(abs / 10000000).toFixed(abs >= 100000000 ? 0 : 2)}Cr`;
  if (abs >= 100000) return `${sign}₹${(abs / 100000).toFixed(abs >= 10000000 ? 0 : 1)}L`;
  if (abs >= 1000) return `${sign}₹${(abs / 1000).toFixed(abs >= 100000 ? 0 : 1)}k`;
  return `${sign}₹${abs}`;
}
